### ISSUE TITLE
Can't add the "GuiTransition" node, no clear error message

### ISSUE THREAD

**Issue by mathieubruguier** [murikistudio/simple-gui-transitions#6]
Good day! I recently found the addon on the AssetLib and it's doing basically everything I've been doing manually, which is awesome.
I added the addon to my project (and enabled in the "Plugins" tab), and I'm able to run the examples as expected. However, when trying to add the `GuiTransition` node to a scene, I'm getting a weird error that's not giving me much:

![image](https://github.com/murikistudio/simple-gui-transitions/assets/792891/b321e8df-e8c2-4aa3-9eaf-f7e08e981d02)

![image](https://github.com/murikistudio/simple-gui-transitions/assets/792891/0e40cb6d-6b81-4a36-b436-474de8d3dfcd)

For context, I'm adding the `GuiTransition` node as a child to a `Control` parent.
As a hack, I can copy the `GuiTransition` node from the example scene and paste it in my scene, and that seems to work, but I don't think that's the way it should be haha.
Am I missing something somewhere?

**Comment by joelgomes1994** [comment]
Hello, @mathieubruguier! Thanks for the report. I tried to install it from the _AssetLib_ on a brand new project, and I **could** reproduce your issue. However, after closing and reopening the project, it works as expected.

Probably I should add to the project's README "reload your project after enabling the plugin", because it must be some issue with the `class_name` of the node.

Could you confirm if it works as expected after the step noted above?

**Comment by mathieubruguier** [comment]
Thank you for the quick response! I figured that could have been the case so I had already restarted Godot once or twice, no dice.
However, it looks like it actually works this morning after restarting my computer! Maybe I didn't restart Godot hard enough 😝 

Sorry for wasting your time with it! Everything's well that ends well. 😄
